---
title: async await catch
date: 2023-04-10 11:20:39
permalink: /pages/b80ae0/
categories: 
  - 学习分类大全
  - 面试
  - 其他
tags: 
  - javascript
author: 
  name: mby
  link: https://blog.csdn.net/weixin_44149219?type=blog
titleTag: 
---
- 写法一(try catch)
```js
function test() {
    return new Promise((resolve, reject) => {
        throw new Error("testError");
    });
}

async function main() {
    try {
        await test();
    } catch (err) {
        console.log(err);
    }
}
main();
``` 
- 写法二(new Promise.catch())
```js
function test() {
    return new Promise((resolve, reject) => {
        resolve("hello world");
    });
}

async function main() {
    let result = await test().catch((err) => {});
    console.log("await后 这里正常打印 说明await后面的代码不会被阻塞");
}
main();
```
```js
function test() {
    return new Promise((resolve, reject) => {
        throw new Error("testError");
    });
}

async function main() {
    let result = await test().catch((err) => {
        console.log(err);
    });

    console.log("await后 这里正常打印 说明await后面的代码不会被阻塞");
}
main();
```
<strong style='color:orange'>以后就不用try catch await了</strong>